# backbone
python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon":96}' --model-name "LLM.CALFModel" --model-hyper-params '{"batch_size": 16, "d_ff": 768, "d_model": 768, "dataset": "Electricity", "dropout": 0.3, "freq": "h", "gpt_layers": 6, "horizon": 96, "is_train": 1, "lr": 0.0005, "n_heads": 4, "norm": true, "num_epochs": 10, "patience": 3, "sampling_rate": 0.05, "seq_len": 512}' --adapter "llm_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/CALF"
python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon":192}' --model-name "LLM.CALFModel" --model-hyper-params '{"batch_size": 16, "d_ff": 768, "d_model": 768, "dataset": "Electricity", "dropout": 0.3, "freq": "h", "gpt_layers": 6, "horizon": 192, "is_train": 1, "lr": 0.0005, "n_heads": 4, "norm": true, "num_epochs": 10, "patience": 3, "sampling_rate": 0.05, "seq_len": 512}' --adapter "llm_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/CALF"
python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon":336}' --model-name "LLM.CALFModel" --model-hyper-params '{"batch_size": 16, "d_ff": 768, "d_model": 768, "dataset": "Electricity", "dropout": 0.3, "freq": "h", "gpt_layers": 6, "horizon": 336, "is_train": 1, "lr": 0.0005, "n_heads": 4, "norm": true, "num_epochs": 10, "patience": 3, "sampling_rate": 0.05, "seq_len": 512}' --adapter "llm_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/CALF"
python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon":720}' --model-name "LLM.CALFModel" --model-hyper-params '{"batch_size": 16, "d_ff": 768, "d_model": 768, "dataset": "Electricity", "dropout": 0.3, "freq": "h", "gpt_layers": 6, "horizon": 720, "is_train": 1, "lr": 0.0005, "n_heads": 4, "norm": true, "num_epochs": 10, "patience": 3, "sampling_rate": 0.05, "seq_len": 512}' --adapter "llm_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/CALF"

# CoRA
python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon":96}' --model-name "LLM.CALFModel" --model-hyper-params '{"batch_size": 16, "d_ff": 768, "d_model": 768, "dataset": "Electricity", "dropout": 0.3, "freq": "h", "gpt_layers": 6, "horizon": 96, "is_train": 1, "lr": 0.0005, "n_heads": 4, "norm": true, "num_epochs": 10, "patience": 3, "sampling_rate": 0.05, "seq_len": 512}' --plugin-hyper-params '{"K": 2, "M": 1, "backbone_lr": 0.0005, "beta": 0.3, "de": 2, "dropout": 0.1, "gama": 0.001, "head_dropout": 0.05, "num_after": 3, "num_before": 2, "plugin_dim": 256, "plugin_lr": 0.0004, "thresold": 0.3}' --adapter "LLM_Plugin_adapter" --eval-backend "sequential" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/CALF"
python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon":192}' --model-name "LLM.CALFModel" --model-hyper-params '{"batch_size": 16, "d_ff": 768, "d_model": 768, "dataset": "Electricity", "dropout": 0.3, "freq": "h", "gpt_layers": 6, "horizon": 192, "is_train": 1, "lr": 0.0005, "n_heads": 4, "norm": true, "num_epochs": 10, "patience": 3, "sampling_rate": 0.05, "seq_len": 512}' --plugin-hyper-params '{"K": 2, "M": 1, "backbone_lr": 0.0005, "beta": 0.25, "de": 2, "dropout": 0.1, "gama": 0.001, "head_dropout": 0.05, "num_after": 3, "num_before": 2, "plugin_dim": 128, "plugin_lr": 0.0002, "thresold": 0.25}' --adapter "LLM_Plugin_adapter" --eval-backend "sequential" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/CALF"
python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon":336}' --model-name "LLM.CALFModel" --model-hyper-params '{"batch_size": 16, "d_ff": 768, "d_model": 768, "dataset": "Electricity", "dropout": 0.3, "freq": "h", "gpt_layers": 6, "horizon": 336, "is_train": 1, "lr": 0.0005, "n_heads": 4, "norm": true, "num_epochs": 10, "patience": 3, "sampling_rate": 0.05, "seq_len": 512}' --plugin-hyper-params '{"K": 2, "M": 1, "backbone_lr": 0.0005, "beta": 0.15, "de": 2, "dropout": 0.1, "gama": 0.001, "head_dropout": 0.05, "num_after": 3, "num_before": 2, "plugin_dim": 256, "plugin_lr": 0.0002, "thresold": 0.3}' --adapter "LLM_Plugin_adapter" --eval-backend "sequential" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/CALF"
python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon":720}' --model-name "LLM.CALFModel" --model-hyper-params '{"batch_size": 16, "d_ff": 768, "d_model": 768, "dataset": "Electricity", "dropout": 0.3, "freq": "h", "gpt_layers": 6, "horizon": 720, "is_train": 1, "lr": 0.0005, "n_heads": 4, "norm": true, "num_epochs": 10, "patience": 3, "sampling_rate": 0.05, "seq_len": 512}' --plugin-hyper-params '{"K": 2, "M": 1, "backbone_lr": 0.0005, "beta": 0.25, "de": 2, "dropout": 0.1, "gama": 0.001, "head_dropout": 0.05, "num_after": 3, "num_before": 2, "plugin_dim": 384, "plugin_lr": 0.0002, "thresold": 0.25}' --adapter "LLM_Plugin_adapter" --eval-backend "sequential" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/CALF"
