# backbone
python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon":96}' --model-name "pre_train.TinyTimeMixer" --model-hyper-params '{"batch_size": 16, "dataset": "Electricity", "freq": "h", "horizon": 96, "is_train": 1, "lr": 0.0001, "norm": true, "num_epochs": 20, "patience": 3, "sampling_rate": 0.05, "seq_len": 512, "target_dim": 321}' --adapter "PreTrain_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/TTM"
python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon":192}' --model-name "pre_train.TinyTimeMixer" --model-hyper-params '{"batch_size": 16, "dataset": "Electricity", "freq": "h", "horizon": 192, "is_train": 1, "lr": 0.0001, "norm": true, "num_epochs": 20, "patience": 3, "sampling_rate": 0.05, "seq_len": 512, "target_dim": 321}' --adapter "PreTrain_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/TTM"
python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon":336}' --model-name "pre_train.TinyTimeMixer" --model-hyper-params '{"batch_size": 16, "dataset": "Electricity", "freq": "h", "horizon": 336, "is_train": 1, "lr": 0.0001, "norm": true, "num_epochs": 20, "patience": 3, "sampling_rate": 0.05, "seq_len": 512, "target_dim": 321}' --adapter "PreTrain_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/TTM"
python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon":720}' --model-name "pre_train.TinyTimeMixer" --model-hyper-params '{"batch_size": 16, "dataset": "Electricity", "freq": "h", "horizon": 720, "is_train": 1, "lr": 0.0001, "norm": true, "num_epochs": 20, "patience": 3, "sampling_rate": 0.05, "seq_len": 512, "target_dim": 321}' --adapter "PreTrain_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/TTM"

# CoRA
python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon":96}' --model-name "pre_train.TinyTimeMixer" --model-hyper-params '{"alpha": 0.0, "batch_size": 16, "dataset": "Electricity", "freq": "h", "horizon": 96, "is_train": 1, "loss": "MSE", "lr": 0.001, "norm": true, "num_epochs": 20, "patience": 3, "sampling_rate": 0.05, "seq_len": 512, "stage1_batch_size": 16, "stage2_batch_size": 16, "target_dim": 321, "train_stages": "plugin,joint"}' --plugin-hyper-params '{"K": 1, "M": 2, "backbone_lr": 0.0001, "beta": 0.0, "de": 1, "dropout": 0.4, "gama": 0.0, "head_dropout": 0.1, "num_after": 4, "num_before": 2, "plugin_dim": 64, "plugin_lr": 2e-05, "thresold": 0.5}' --adapter "Plugin_adapter" --eval-backend "sequential" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/TTM"
python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon":192}' --model-name "pre_train.TinyTimeMixer" --model-hyper-params '{"alpha": 0.0, "batch_size": 16, "dataset": "Electricity", "freq": "h", "horizon": 192, "is_train": 1, "loss": "MSE", "lr": 0.001, "norm": true, "num_epochs": 20, "patience": 3, "sampling_rate": 0.05, "seq_len": 512, "stage1_batch_size": 16, "stage2_batch_size": 16, "target_dim": 321, "train_stages": "plugin,joint"}' --plugin-hyper-params '{"K": 2, "M": 2, "backbone_lr": 0.0001, "beta": 0.2, "de": 2, "dropout": 0.1, "gama": 0.0005, "head_dropout": 0.05, "num_after": 2, "num_before": 1, "plugin_dim": 64, "plugin_lr": 0.0001, "thresold": 0.3}' --adapter "Plugin_adapter" --eval-backend "sequential" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/TTM"
python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon":336}' --model-name "pre_train.TinyTimeMixer" --model-hyper-params '{"alpha": 0.0, "batch_size": 16, "dataset": "Electricity", "freq": "h", "horizon": 336, "is_train": 1, "loss": "MSE", "lr": 0.001, "norm": true, "num_epochs": 20, "patience": 3, "sampling_rate": 0.05, "seq_len": 512, "stage1_batch_size": 16, "stage2_batch_size": 16, "target_dim": 321, "train_stages": "plugin,joint"}' --plugin-hyper-params '{"K": 1, "M": 2, "backbone_lr": 0.0001, "beta": 0.0, "de": 1, "dropout": 0.4, "gama": 0.0, "head_dropout": 0.1, "num_after": 4, "num_before": 2, "plugin_dim": 64, "plugin_lr": 2e-05, "thresold": 0.5}' --adapter "Plugin_adapter" --eval-backend "sequential" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/TTM"
python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon":720}' --model-name "pre_train.TinyTimeMixer" --model-hyper-params '{"alpha": 0.0, "batch_size": 16, "dataset": "Electricity", "freq": "h", "horizon": 720, "is_train": 1, "loss": "MSE", "lr": 0.001, "norm": true, "num_epochs": 20, "patience": 3, "sampling_rate": 0.05, "seq_len": 512, "stage1_batch_size": 16, "stage2_batch_size": 16, "target_dim": 321, "train_stages": "plugin,joint"}' --plugin-hyper-params '{"K": 2, "M": 2, "backbone_lr": 0.0001, "beta": 0.2, "de": 2, "dropout": 0.2, "gama": 0.001, "head_dropout": 0.05, "num_after": 3, "num_before": 2, "plugin_dim": 128, "plugin_lr": 0.0001, "thresold": 0.3}' --adapter "Plugin_adapter" --eval-backend "sequential" --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/TTM"
