# backbone
python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon":96}' --model-name "LLM.CALFModel" --model-hyper-params '{"batch_size": 64, "d_ff": 768, "d_model": 768, "dataset": "ETTh2", "dropout": 0.3, "freq": "h", "gpt_layers": 6, "horizon": 96, "is_train": 1, "lr": 0.0005, "n_heads": 4, "norm": true, "sampling_rate": 0.05, "seq_len": 336, "target_dim": 7}' --adapter "llm_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/CALF"
python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon":192}' --model-name "LLM.CALFModel" --model-hyper-params '{"batch_size": 64, "d_ff": 768, "d_model": 768, "dataset": "ETTh2", "dropout": 0.3, "freq": "h", "gpt_layers": 6, "horizon": 192, "is_train": 1, "lr": 0.0005, "n_heads": 4, "norm": true, "sampling_rate": 0.05, "seq_len": 336, "target_dim": 7}' --adapter "llm_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/CALF"
python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon":336}' --model-name "LLM.CALFModel" --model-hyper-params '{"batch_size": 64, "d_ff": 768, "d_model": 768, "dataset": "ETTh2", "dropout": 0.3, "freq": "h", "gpt_layers": 6, "horizon": 336, "is_train": 1, "lr": 0.0005, "n_heads": 4, "norm": true, "sampling_rate": 0.05, "seq_len": 336, "target_dim": 7}' --adapter "llm_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/CALF"
python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon":720}' --model-name "LLM.CALFModel" --model-hyper-params '{"batch_size": 64, "d_ff": 768, "d_model": 768, "dataset": "ETTh2", "dropout": 0.3, "freq": "h", "gpt_layers": 6, "horizon": 720, "is_train": 1, "lr": 0.0005, "n_heads": 4, "norm": true, "sampling_rate": 0.05, "seq_len": 336, "target_dim": 7}' --adapter "llm_adapter" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/CALF"

# CoRA
python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon":96}' --model-name "LLM.CALFModel" --model-hyper-params '{"batch_size": 64, "d_ff": 768, "d_model": 768, "dataset": "ETTh2", "dropout": 0.3, "freq": "h", "gpt_layers": 6, "horizon": 96, "is_train": 1, "lr": 0.0005, "n_heads": 4, "norm": true, "num_epochs": 10, "patience": 3, "sampling_rate": 0.05, "seq_len": 336, "target_dim": 7}' --plugin-hyper-params '{"K": 3, "M": 1, "backbone_lr": 0.00035, "beta": 0.35, "de": 3, "dropout": 0.15, "gama": 0.001, "head_dropout": 0.05, "num_after": 4, "num_before": 2, "plugin_dim": 384, "plugin_lr": 0.00015, "thresold": 0.3}' --adapter "LLM_Plugin_adapter" --eval-backend "sequential" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/CALF"
python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon":192}' --model-name "LLM.CALFModel" --model-hyper-params '{"batch_size": 64, "d_ff": 768, "d_model": 768, "dataset": "ETTh2", "dropout": 0.3, "freq": "h", "gpt_layers": 6, "horizon": 192, "is_train": 1, "lr": 0.0005, "n_heads": 4, "norm": true, "num_epochs": 100, "patience": 5, "sampling_rate": 0.05, "seq_len": 336, "target_dim": 7}' --plugin-hyper-params '{"K": 3, "M": 1, "backbone_lr": 0.00025, "beta": 0.5, "de": 2, "dropout": 0.3, "gama": 0.0005, "head_dropout": 0.3, "num_after": 3, "num_before": 3, "plugin_dim": 64, "plugin_lr": 0.0002, "thresold": 0.2}' --adapter "LLM_Plugin_adapter" --eval-backend "sequential" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/CALF"
python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon":336}' --model-name "LLM.CALFModel" --model-hyper-params '{"batch_size": 64, "d_ff": 768, "d_model": 768, "dataset": "ETTh2", "dropout": 0.3, "freq": "h", "gpt_layers": 6, "horizon": 336, "is_train": 1, "lr": 0.0005, "n_heads": 4, "norm": true, "num_epochs": 100, "patience": 5, "sampling_rate": 0.05, "seq_len": 336, "target_dim": 7}' --plugin-hyper-params '{"K": 1, "M": 1, "backbone_lr": 0.0005, "beta": 0.4, "de": 3, "dropout": 0.3, "gama": 0.002, "head_dropout": 0.3, "num_after": 5, "num_before": 3, "plugin_dim": 32, "plugin_lr": 5e-05, "thresold": 0.35}' --adapter "LLM_Plugin_adapter" --eval-backend "sequential" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/CALF"
python ./scripts/run.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon":720}' --model-name "LLM.CALFModel" --model-hyper-params '{"batch_size": 64, "d_ff": 768, "d_model": 768, "dataset": "ETTh2", "dropout": 0.3, "freq": "h", "gpt_layers": 6, "horizon": 720, "is_train": 1, "lr": 0.0005, "n_heads": 4, "norm": true, "num_epochs": 10, "patience": 3, "sampling_rate": 0.05, "seq_len": 336, "target_dim": 7}' --plugin-hyper-params '{"K": 1, "M": 1, "backbone_lr": 0.00075, "beta": 0.3, "de": 1, "dropout": 0.1, "gama": 0.001, "head_dropout": 0.05, "num_after": 2, "num_before": 1, "plugin_dim": 192, "plugin_lr": 0.0002, "thresold": 0.3}' --adapter "LLM_Plugin_adapter" --eval-backend "sequential" --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/CALF"
